name: 'MTCVCTM - Generate VCTM'
description: 'Generate Verifiable Credential Type Metadata from Markdown files'
author: 'sirosfoundation'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  input-dir:
    description: 'Directory containing markdown files'
    required: false
    default: '.'
  output-dir:
    description: 'Output directory for VCTM files'
    required: false
    default: '.'
  base-url:
    description: 'Base URL for generating image URLs with integrity'
    required: false
    default: ''
  vctm-branch:
    description: 'Branch name to commit VCTM files to'
    required: false
    default: 'vctm'
  commit-message:
    description: 'Commit message for VCTM updates'
    required: false
    default: 'Update VCTM files [skip ci]'
  github-token:
    description: 'GitHub token for pushing to vctm branch'
    required: false
    default: ${{ github.token }}
  inline-images:
    description: 'Embed images as base64 data URLs in VCTM files'
    required: false
    default: 'false'

outputs:
  registry-path:
    description: 'Path to the generated registry file'
    value: ${{ steps.generate.outputs.registry-path }}
  credential-count:
    description: 'Number of credentials processed'
    value: ${{ steps.generate.outputs.credential-count }}

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build mtcvctm
      shell: bash
      run: |
        cd ${{ github.action_path }}
        go build -o mtcvctm ./cmd/mtcvctm

    - name: Generate VCTM files
      id: generate
      shell: bash
      run: |
        INLINE_FLAG=""
        if [ "${{ inputs.inline-images }}" = "true" ]; then
          INLINE_FLAG="--inline-images"
        fi
        
        ${{ github.action_path }}/mtcvctm batch \
          --input "${{ inputs.input-dir }}" \
          --output "${{ inputs.output-dir }}" \
          --base-url "${{ inputs.base-url }}" \
          --vctm-branch "${{ inputs.vctm-branch }}" \
          --commit-message "${{ inputs.commit-message }}" \
          $INLINE_FLAG
        
        echo "registry-path=${{ inputs.output-dir }}/.well-known/vctm-registry.json" >> $GITHUB_OUTPUT

    - name: Configure Git
      if: inputs.vctm-branch != ''
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit and push to vctm branch
      if: inputs.vctm-branch != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        VCTM_BRANCH: ${{ inputs.vctm-branch }}
        COMMIT_MSG: ${{ inputs.commit-message }}
      run: |
        # Save output directory contents to temp location
        TEMP_DIR=$(mktemp -d)
        cp -r "$OUTPUT_DIR"/. "$TEMP_DIR"/
        
        # Create orphan branch with only output contents at root
        git checkout --orphan "$VCTM_BRANCH" 2>/dev/null || git switch --orphan "$VCTM_BRANCH"
        git rm -rf . 2>/dev/null || true
        
        # Copy output contents to repo root (including hidden dirs like .well-known)
        cp -r "$TEMP_DIR"/. .
        rm -rf "$TEMP_DIR"
        
        git add -A
        git commit -m "$COMMIT_MSG" || echo "No changes to commit"
        git push origin "$VCTM_BRANCH" --force
